### ISSUE TITLE
Global-Leak in outdated dependency to `ee-types`.

### ISSUE THREAD

**Issue by rcky** [eventEmitter/facr#2]
The referenced version 1 of `ee-types` leaks a global variable `Class` due to a missing comma in the `types.js` and should therefore be updated.

**Comment by rcky** [comment]
Moved to corresponding package https://github.com/eventEmitter/async-method/issues/2

**Comment by linaGirl** [comment]
@rcky i just published [version 1.0.1](https://www.npmjs.com/package/facr) which gets rid of the dependency. Be aware that the callback interface was removed: all methods return now promises.
